In [2]:
import numpy as np
a = np.random.randint(1, 21, [3, 3])
a

array([[12, 16, 11],
       [ 7, 11, 17],
       [ 2, 13,  6]])

In [19]:
a = np.random.randint(10, 101, [2, 2])
sum_of_diagonal = sum(np.diag(a))

InvertedA = np.fliplr(a)
sum_of_antidiagonal = sum(np.diag(InvertedA))

a, InvertedA

(array([[61, 74],
        [94, 33]]),
 array([[74, 61],
        [33, 94]]))

In [20]:
sum_of_diagonal, sum_of_antidiagonal

(np.int64(94), np.int64(168))

using Conditions For Numpy Arrays

In [15]:
x = np.arange(1, 101)

true_false_arr = (x % 3 == 0) & (x % 5 != 0)

x[true_false_arr]

array([ 3,  6,  9, 12, 18, 21, 24, 27, 33, 36, 39, 42, 48, 51, 54, 57, 63,
       66, 69, 72, 78, 81, 84, 87, 93, 96, 99])

Flatten Sort and Find

Flattening into a 1D array for a MultiDimensional Array using ndarray.ravel(array)

In [13]:
a = np.random.randint(10, 101, [3, 3])
print(a)
b = a.flatten()
print(b)

b.sort()
print(b)

b[::-1][:3], b[-3:]

[[55 14 46]
 [80 64 52]
 [98 96 26]]
[55 14 46 80 64 52 98 96 26]
[14 26 46 52 55 64 80 96 98]


(array([98, 96, 80]), array([80, 96, 98]))

Broadcasting and Scaling

In [ ]:
np.random.randint()